///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, concepts, understanding
:rootdir: {docdir}/concepts

= Overview of EclipseLink

This chapter describes EclipseLink and its key features: the components
that are included with EclipseLink, metadata, application architectures,
mappings, and the API.

This chapter includes the following sections:

// == Understanding EclipseLink
:sectnums:
include::{rootdir}/general001.adoc[]

// == Key Features
:sectnums:
include::{rootdir}/general002.adoc[]

// == Key Concepts
:sectnums:
include::{rootdir}/general003.adoc[]

// == Key Components
:sectnums:
include::{rootdir}/general004.adoc[]

// == Key Tools
:sectnums:
include::{rootdir}/general005.adoc[]
