///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

= Introduction
:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, introduction
:rootdir: {docdir}/jpa/extensions

// == List of Examples
:sectnums:
include::{rootdir}/loe.adoc[]

// == Preface
:sectnums:
include::{rootdir}/preface.adoc[]

// == Introduction
:sectnums:
include::{rootdir}/introduction.adoc[]

// == Annotation Extensions Reference
:sectnums:
include::{rootdir}/annotations_ref.adoc[]

// == Java Persistence Query Language Extensions
:sectnums:
include::{rootdir}/jpql.adoc[]

// == JPA Query Customization Extensions
:sectnums:
include::{rootdir}/queryhints.adoc[]

// == Persistence Property Extensions Reference
:sectnums:
include::{rootdir}/persistenceproperties_ref.adoc[]

// == eclipselink-orm.xml Schema Reference
include::{rootdir}/schema.adoc[]