///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

=== The Use Cases

The use cases documented in this guide are as follows:

* xref:{relativedir}/install.adoc#CHDIGBJC[Chapter 2, "Installing EclipseLink"] - How
to download and install EclipseLink.
* xref:{relativedir}/tlandwls.adoc#BABHCJBG[Chapter 3, "Using EclipseLink with WebLogic
Server"] - How to use EclipseLink with WebLogic Server.
* xref:{relativedir}/tlandgs.adoc#BABDGFIC[Chapter 4, "Using EclipseLink with GlassFish
Server"] - How to use EclipseLink with GlassFish Server.
* xref:{relativedir}/jboss.adoc#BEIEIJAE[Chapter 5, "Using EclipseLink with JBoss 7
Application Server"] - How to use EclipseLink with JBoss 7 Application
Server.
* xref:{relativedir}/websphere.adoc#CFHHEHJG[Chapter 6, "Using EclipseLink with IBM
WebSphere Application Server"] - How to use EclipseLink with IBM
WebSphere Application Server.
* xref:{relativedir}/migrnativetoplink.adoc#BCGDEBBB[Chapter 7, "Migrating from Native
TopLink"] - How to how to migrate applications using native EclipseLink
object-relational mapping (ORM) API to the current EclipseLink API.
* xref:{relativedir}/migrhib.adoc#CHDFDCII[Migrating from Hibernate to EclipseLink] -
How to migrate applications from using Hibernate JPA to using
EclipseLink JPA.
* xref:{relativedir}/usingmultipledbs.adoc#BABJAFII[Chapter 9, "Using Multiple
Databases with a Composite Persistence Unit"] - How to expose multiple
persistence units (each with unique sets of entity types) as a single
persistence context.
* xref:{relativedir}/scaling.adoc#CHDCAFDB[Chapter 10, "Scaling Applications in
Clusters"] - How to configure EclipseLink applications to ensure
scalability in clustered application server environments.
* xref:{relativedir}/saas.adoc#CIADHEBF[Chapter 11, "Providing Software as a Service"]
- Overview of EclipseLink Software as a Service (SaaS) features..
* xref:{relativedir}/extensible.adoc#CIAEIEAI[Chapter 12, "Making JPA Entities and JAXB
Beans Extensible"] - How to make JPA entities or JAXB beans extensible.
* xref:{relativedir}/metadatasource.adoc#BABGDEGB[Chapter 13, "Using an External
MetaData Source"] - How to use an external metadata source.
* xref:{relativedir}/multitenancy.adoc#CHDBJCJA[Chapter 14, "Tenant Isolation Using
EclipseLink"] - How to support multiple application tenants who share
data sources, including tables and schemas.
* xref:{relativedir}/jpatoxml.adoc#CIHGJCIH[Chapter 15, "Mapping JPA to XML"] - How to
map JPA entities to XML using EclipseLink MOXy.
* xref:{relativedir}/testingjpa.adoc#BABEBCCJ[Chapter 17, "Testing JPA Outside a
Container"] - How to test your EclipseLink JPA application outside the
container.
* xref:{relativedir}/performance.adoc#BBAGGDED[Chapter 18, "Enhancing Performance"] -
Getting the best performance out of EclipseLink.
* xref:{relativedir}/restful_jpa.adoc#CHDGHJID[Chapter 19, "Exposing JPA Entities
Through RESTful Data Services"] - How to expose entities through RESTful
services using EclipseLink Jakarta Persistence API for RESTful Services
(JPA-RS).
* xref:{relativedir}/qcn.adoc#CHDDAEJB[Chapter 20, "Using Database Events to Invalidate
the Cache"] - How to use EclipseLink Database Change Notification (DCN)
for caching with a shared database in JPA.
* xref:{relativedir}/nonrelational_db.adoc#BGBCIABF[Chapter 21, "Using EclipseLink with
NoSQL Databases"] - How to use EclipseLink to map objects to
non-relational (that is, no SQL) data sources.
